[package]
name = "elefren"
version = "0.16.0"

description = "A wrapper around the Mastodon API."
authors = ["Aaron Power <theaaronepower@gmail.com>", "Paul Woolcock <paul@woolcock.us>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/pwoolcoc/elefren.git"
keywords = ["api", "web", "social", "mastodon", "wrapper"]
categories = ["web-programming", "web-programming::http-client", "api-bindings"]

[dependencies]
doc-comment = "0.1"
isolang = { version = "0.2", features = ["serde_serialize"] }
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_urlencoded = "0.5.3"
url = "1"
tap-reader = "1"
try_from = "0.3.2"
toml = { version = "0.4.6", optional = true }
hyper-old-types = "0.11.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[features]
default-features = []
json = []
all = ["toml", "json"]

[build-dependencies]
skeptic = "0.13.3"

[dev-dependencies]
skeptic = "0.13.3"
tempfile = "3.0.3"
indoc = "0.3.1"
pretty_env_logger = "0.2.4"

[package.metadata.docs.rs]
features = ["all"]
